export const ADD_SERVICE = 'ADD_SERVICE';
export const REMOVE_SERVICE = 'REMOVE_SERVICE';
export const CHANGE_SERVICE_FIELD = 'CHANGE_SERVICE_FIELD';
export const EDIT_SERVICE = 'EDIT_SERVICE';
export const CANCEL_SERVICE_EDIT = 'CANCEL_SERVICE_EDIT';
export const SAVE_SERVICE = 'SAVE_SERVICE';