export const REFRESH_DETAILS = 'REFRESH_DETAILS';
export const SEARCH_DATA_REQUEST = 'SEARCH_DATA_REQUEST';
export const SEARCH_DETAILS_SUCCESS = 'SEARCH_DETAILS_SUCCESS';
export const SEARCH_DETAILS_FAILURE = 'SEARCH_DETAILS_FAILURE';