export const REFRESH_DETAILS = 'REFRESH_DETAILS';
export const SEARCH_DETAILS_REQUEST = 'SEARCH_DETAILS_REQUEST';
export const SEARCH_DETAILS_SUCCESS = 'SEARCH_DETAILS_SUCCESS';
export const SEARCH_DETAILS_FAILURE = 'SEARCH_DETAILS_FAILURE';

export const REFRESH_ITEMS = 'REFRESH_ITEMS';
export const SEARCH_ITEMS_REQUEST = 'SEARCH_ITEMS_REQUEST';
export const SEARCH_ITEMS_SUCCESS = 'SEARCH_ITEMS_SUCCESS';
export const SEARCH_ITEMS_FAILURE = 'SEARCH_ITEMS_FAILURE';